#!/bin/bash -l

set -eu

cd "$APP_HOME"

APP_N8N_DEPENDENCIES_LIST="${APP_N8N_DEPENDENCIES:-}"
APP_N8N_DEPENDENCIES_LIST="${APP_N8N_DEPENDENCIES_LIST//,/ }"

if [ -n "${APP_N8N_DEPENDENCIES_LIST// /}" ]; then
  pnpm add --prod ${APP_N8N_DEPENDENCIES_LIST}
fi
